# Generated by Django 4.1.5 on 2023-01-20 23:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adjunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=None, max_length=50, unique=True)),
                ('imagen', models.ImageField(default='adjunto.png', upload_to='adjuntos')),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.date(2023, 1, 20))),
                ('concepto', models.CharField(blank=None, max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Configuracion_Fuente_Informacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buscar_Titulo', models.CharField(blank=None, max_length=200)),
                ('buscar_Contenido', models.CharField(blank=None, max_length=200)),
                ('buscar_Imagenes', models.CharField(blank=None, max_length=200)),
                ('buscar_links', models.CharField(blank=None, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Contenido_Original',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_acceso', models.DateField(blank=None, default=datetime.datetime(2023, 1, 20, 23, 22, 13, 779903, tzinfo=datetime.timezone.utc))),
                ('contenido', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=None, max_length=50, unique=True)),
                ('idioma', models.CharField(blank=None, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(default='@gmail.com', max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('is_superuser', models.BooleanField()),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Fuente_Informacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=None, max_length=100)),
                ('URL', models.URLField(blank=None)),
                ('tipo', models.CharField(max_length=50)),
                ('es_parte_de', models.PositiveBigIntegerField()),
                ('nivel', models.PositiveIntegerField()),
                ('fecha', models.DateField(default=datetime.datetime(2023, 1, 20, 23, 22, 13, 780905, tzinfo=datetime.timezone.utc))),
                ('idPais', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Modelo.pais')),
            ],
        ),
        migrations.CreateModel(
            name='Contenido_Procesado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=None, max_length=100, unique=True)),
                ('fecha_Creacion', models.DateField(blank=None, default=datetime.datetime(2023, 1, 20, 23, 22, 13, 781902, tzinfo=datetime.timezone.utc))),
                ('contenido', models.TextField()),
                ('anotacion', models.TextField()),
                ('idAdjunto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Modelo.adjunto')),
                ('idCategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Modelo.categoria')),
                ('idContenido_Original', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Modelo.contenido_original')),
                ('idFuente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Modelo.fuente_informacion')),
            ],
        ),
    ]
