# Generated by Django 4.1.7 on 2023-05-10 03:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adjunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=None, max_length=250, unique=True)),
                ('imagen', models.ImageField(default='adjunto.png', max_length=250, upload_to='adjuntos/')),
                ('URL', models.URLField(blank=None, unique=True)),
                ('fecha_creacion', models.DateField(blank=None, default=datetime.datetime(2023, 5, 10, 3, 40, 50, 500014, tzinfo=datetime.timezone.utc))),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.date(2023, 5, 10))),
                ('concepto', models.CharField(blank=None, max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contenido_Original',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_acceso', models.DateField(blank=None, default=datetime.datetime(2023, 5, 10, 3, 40, 50, 501014, tzinfo=datetime.timezone.utc))),
                ('contenido', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=None, max_length=50, unique=True)),
                ('idioma', models.CharField(blank=None, max_length=250)),
                ('fecha_creacion', models.DateField(blank=None, default=datetime.datetime(2023, 5, 10, 3, 40, 50, 499263, tzinfo=datetime.timezone.utc))),
            ],
        ),
        migrations.CreateModel(
            name='Fuente_Informacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=None, max_length=100)),
                ('URL', models.URLField(blank=None, unique=True)),
                ('tipo', models.CharField(max_length=50)),
                ('nivel', models.PositiveIntegerField(default=1)),
                ('fecha', models.DateField(default=datetime.datetime(2023, 5, 10, 3, 40, 50, 500014, tzinfo=datetime.timezone.utc))),
                ('idPadre', models.IntegerField(default=0)),
                ('idPais', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Modelo.pais')),
            ],
        ),
        migrations.CreateModel(
            name='Contenido_Procesado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=None, max_length=100, unique=True)),
                ('fecha_Creacion', models.DateField(blank=None, default=datetime.datetime(2023, 5, 10, 3, 40, 50, 501014, tzinfo=datetime.timezone.utc))),
                ('contenido', models.TextField()),
                ('anotacion', models.TextField()),
                ('idAdjunto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Modelo.adjunto')),
                ('idCategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Modelo.categoria')),
                ('idContenido_Original', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Modelo.contenido_original')),
            ],
        ),
        migrations.AddField(
            model_name='contenido_original',
            name='idFuente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Modelo.fuente_informacion'),
        ),
        migrations.CreateModel(
            name='Configuracion_Fuente_Informacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buscar_Titulo', models.CharField(blank=None, max_length=200)),
                ('buscar_Contenido', models.CharField(blank=None, max_length=200)),
                ('buscar_Imagenes', models.CharField(blank=None, max_length=200)),
                ('buscar_links', models.CharField(blank=None, max_length=200)),
                ('id_fuente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Modelo.fuente_informacion')),
            ],
        ),
    ]
