# Generated by Django 4.1.7 on 2023-05-13 15:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Modelo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adjunto',
            name='fecha_creacion',
            field=models.DateField(blank=None, default=datetime.datetime(2023, 5, 13, 15, 45, 48, 970146, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='adjunto',
            name='imagen',
            field=models.ImageField(default='adjunto.png', max_length=250, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='fecha',
            field=models.DateField(default=datetime.date(2023, 5, 13)),
        ),
        migrations.AlterField(
            model_name='contenido_original',
            name='fecha_acceso',
            field=models.DateField(blank=None, default=datetime.datetime(2023, 5, 13, 15, 45, 48, 971146, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='contenido_procesado',
            name='fecha_Creacion',
            field=models.DateField(blank=None, default=datetime.datetime(2023, 5, 13, 15, 45, 48, 971146, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='fuente_informacion',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2023, 5, 13, 15, 45, 48, 970146, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='pais',
            name='fecha_creacion',
            field=models.DateField(blank=None, default=datetime.datetime(2023, 5, 13, 15, 45, 48, 969545, tzinfo=datetime.timezone.utc)),
        ),
    ]
