# Generated by Django 3.2.3 on 2022-04-27 21:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Modelo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2022, 4, 27, 21, 55, 41, 131732, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='contenido_original',
            name='fecha_acceso',
            field=models.DateField(blank=None, default=datetime.datetime(2022, 4, 27, 21, 55, 41, 131732, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='contenido_procesado',
            name='fecha_Creacion',
            field=models.DateField(blank=None, default=datetime.datetime(2022, 4, 27, 21, 55, 41, 131732, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='fuente_informacion',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2022, 4, 27, 21, 55, 41, 131732, tzinfo=utc)),
        ),
    ]
