# Generated by Django 4.1.5 on 2023-01-22 19:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Modelo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fuente_informacion',
            name='es_parte_de',
        ),
        migrations.AlterField(
            model_name='categoria',
            name='fecha',
            field=models.DateField(default=datetime.date(2023, 1, 22)),
        ),
        migrations.AlterField(
            model_name='contenido_original',
            name='fecha_acceso',
            field=models.DateField(blank=None, default=datetime.datetime(2023, 1, 22, 19, 33, 15, 619483, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='contenido_procesado',
            name='fecha_Creacion',
            field=models.DateField(blank=None, default=datetime.datetime(2023, 1, 22, 19, 33, 15, 622468, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='fuente_informacion',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2023, 1, 22, 19, 33, 15, 621471, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='fuente_informacion',
            name='nivel',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('URL', models.URLField(blank=None)),
                ('fecha', models.DateField(default=datetime.datetime(2023, 1, 22, 19, 33, 15, 622468, tzinfo=datetime.timezone.utc))),
                ('es_parte_de', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Modelo.fuente_informacion')),
            ],
        ),
    ]
