# Generated by Django 4.1.7 on 2023-05-13 15:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Modelo', '0002_alter_adjunto_fecha_creacion_alter_adjunto_imagen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adjunto',
            name='fecha_creacion',
            field=models.DateField(blank=None, default=datetime.datetime(2023, 5, 13, 15, 53, 44, 160796, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='contenido_original',
            name='fecha_acceso',
            field=models.DateField(blank=None, default=datetime.datetime(2023, 5, 13, 15, 53, 44, 161679, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='contenido_procesado',
            name='fecha_Creacion',
            field=models.DateField(blank=None, default=datetime.datetime(2023, 5, 13, 15, 53, 44, 162678, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='fuente_informacion',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2023, 5, 13, 15, 53, 44, 161679, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='pais',
            name='fecha_creacion',
            field=models.DateField(blank=None, default=datetime.datetime(2023, 5, 13, 15, 53, 44, 160796, tzinfo=datetime.timezone.utc)),
        ),
    ]
