# Generated by Django 4.1.5 on 2023-01-22 19:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Modelo', '0002_remove_fuente_informacion_es_parte_de_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion_fuente_informacion',
            name='id_fuente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Modelo.fuente_informacion'),
        ),
        migrations.AlterField(
            model_name='contenido_original',
            name='fecha_acceso',
            field=models.DateField(blank=None, default=datetime.datetime(2023, 1, 22, 19, 46, 23, 440262, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='contenido_procesado',
            name='fecha_Creacion',
            field=models.DateField(blank=None, default=datetime.datetime(2023, 1, 22, 19, 46, 23, 442265, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='fuente_informacion',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2023, 1, 22, 19, 46, 23, 441259, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='links',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2023, 1, 22, 19, 46, 23, 441259, tzinfo=datetime.timezone.utc)),
        ),
    ]
