# Generated by Django 4.1.5 on 2023-01-22 20:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Modelo', '0003_configuracion_fuente_informacion_id_fuente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenido_original',
            name='fecha_acceso',
            field=models.DateField(blank=None, default=datetime.datetime(2023, 1, 22, 20, 9, 46, 225736, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='contenido_procesado',
            name='fecha_Creacion',
            field=models.DateField(blank=None, default=datetime.datetime(2023, 1, 22, 20, 9, 46, 227730, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='fuente_informacion',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2023, 1, 22, 20, 9, 46, 226733, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='links',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2023, 1, 22, 20, 9, 46, 227730, tzinfo=datetime.timezone.utc)),
        ),
    ]
