# Generated by Django 4.1.7 on 2023-06-11 21:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Modelo', '0003_alter_adjunto_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenido_procesado',
            name='html',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='adjunto',
            name='fecha_creacion',
            field=models.DateField(blank=None, default=datetime.datetime(2023, 6, 11, 21, 50, 35, 906212, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='fecha',
            field=models.DateField(default=datetime.date(2023, 6, 11)),
        ),
        migrations.AlterField(
            model_name='contenido_original',
            name='fecha_acceso',
            field=models.DateField(blank=None, default=datetime.datetime(2023, 6, 11, 21, 50, 35, 907213, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='contenido_procesado',
            name='fecha_Creacion',
            field=models.DateField(blank=None, default=datetime.datetime(2023, 6, 11, 21, 50, 35, 907213, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='fuente_informacion',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2023, 6, 11, 21, 50, 35, 906212, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='pais',
            name='fecha_creacion',
            field=models.DateField(blank=None, default=datetime.datetime(2023, 6, 11, 21, 50, 35, 905177, tzinfo=datetime.timezone.utc)),
        ),
    ]
