# Generated by Django 4.1.7 on 2023-06-28 03:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Modelo', '0004_contenido_procesado_html_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adjunto',
            name='fecha_creacion',
            field=models.DateField(blank=None, default=datetime.datetime(2023, 6, 28, 3, 12, 17, 70665, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='concepto',
            field=models.CharField(blank=None, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='fecha',
            field=models.DateField(default=datetime.date(2023, 6, 28)),
        ),
        migrations.AlterField(
            model_name='contenido_original',
            name='fecha_acceso',
            field=models.DateField(blank=None, default=datetime.datetime(2023, 6, 28, 3, 12, 17, 71677, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='contenido_procesado',
            name='fecha_Creacion',
            field=models.DateField(blank=None, default=datetime.datetime(2023, 6, 28, 3, 12, 17, 71677, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='contenido_procesado',
            name='titulo',
            field=models.CharField(blank=None, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='fuente_informacion',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2023, 6, 28, 3, 12, 17, 71677, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='fuente_informacion',
            name='nombre',
            field=models.CharField(blank=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='fuente_informacion',
            name='tipo',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='pais',
            name='fecha_creacion',
            field=models.DateField(blank=None, default=datetime.datetime(2023, 6, 28, 3, 12, 17, 70665, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='pais',
            name='nombre',
            field=models.CharField(blank=None, max_length=150, unique=True),
        ),
        migrations.DeleteModel(
            name='Configuracion_Fuente_Informacion',
        ),
    ]
