# Generated by Django 4.1.5 on 2023-02-24 00:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Modelo', '0005_remove_contenido_procesado_idfuente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenido_original',
            name='fecha_acceso',
            field=models.DateField(blank=None, default=datetime.datetime(2023, 2, 24, 0, 24, 20, 105931, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='contenido_original',
            name='idFuente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Modelo.fuente_informacion'),
        ),
        migrations.AlterField(
            model_name='contenido_procesado',
            name='fecha_Creacion',
            field=models.DateField(blank=None, default=datetime.datetime(2023, 2, 24, 0, 24, 20, 105931, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='fuente_informacion',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2023, 2, 24, 0, 24, 20, 105158, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='links',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2023, 2, 24, 0, 24, 20, 105158, tzinfo=datetime.timezone.utc)),
        ),
    ]
