# Generated by Django 4.1.7 on 2023-03-25 19:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Modelo', '0009_alter_contenido_original_contenido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adjunto',
            name='imagen',
            field=models.ImageField(default='adjunto.png', max_length=250, upload_to='adjuntos'),
        ),
        migrations.AlterField(
            model_name='adjunto',
            name='nombre',
            field=models.CharField(blank=None, max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='contenido_original',
            name='fecha_acceso',
            field=models.DateField(blank=None, default=datetime.datetime(2023, 3, 25, 19, 37, 13, 335326, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='contenido_procesado',
            name='fecha_Creacion',
            field=models.DateField(blank=None, default=datetime.datetime(2023, 3, 25, 19, 37, 13, 338320, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='fuente_informacion',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2023, 3, 25, 19, 37, 13, 329344, tzinfo=datetime.timezone.utc)),
        ),
    ]
