# Generated by Django 4.1.7 on 2023-03-29 05:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Modelo', '0016_alter_adjunto_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adjunto',
            name='imagen',
            field=models.ImageField(default='adjunto.png', max_length=250, upload_to='adjuntos/'),
        ),
        migrations.AlterField(
            model_name='contenido_original',
            name='fecha_acceso',
            field=models.DateField(blank=None, default=datetime.datetime(2023, 3, 29, 5, 45, 28, 533262, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='contenido_procesado',
            name='fecha_Creacion',
            field=models.DateField(blank=None, default=datetime.datetime(2023, 3, 29, 5, 45, 28, 533262, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='fuente_informacion',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2023, 3, 29, 5, 45, 28, 532271, tzinfo=datetime.timezone.utc)),
        ),
    ]
