# Generated by Django 4.1.7 on 2023-04-09 23:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Modelo', '0017_alter_adjunto_imagen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adjunto',
            name='fecha_creacion',
            field=models.DateField(blank=None, default=datetime.datetime(2023, 4, 9, 23, 9, 6, 804387, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='pais',
            name='fecha_creacion',
            field=models.DateField(blank=None, default=datetime.datetime(2023, 4, 9, 23, 9, 6, 804387, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='fecha',
            field=models.DateField(default=datetime.date(2023, 4, 9)),
        ),
        migrations.AlterField(
            model_name='contenido_original',
            name='fecha_acceso',
            field=models.DateField(blank=None, default=datetime.datetime(2023, 4, 9, 23, 9, 6, 804387, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='contenido_procesado',
            name='fecha_Creacion',
            field=models.DateField(blank=None, default=datetime.datetime(2023, 4, 9, 23, 9, 6, 804387, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='fuente_informacion',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2023, 4, 9, 23, 9, 6, 804387, tzinfo=datetime.timezone.utc)),
        ),
    ]
